= bespoke-builds
Dan Allen <https://github.com/mojavelinux>
// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:outfilesuffix: .adoc
//:status:
endif::[]
// Variables:
:release-version: master
// URIs:
:uri-raw-file-base: https://raw.githubusercontent.com/opendevise/bespoke-builds/{release-version}

ifdef::status[]
image:https://img.shields.io/npm/v/bespoke-builds.svg[npm package, link=https://www.npmjs.com/package/bespoke-builds]
image:https://img.shields.io/travis/opendevise/bespoke-builds/master.svg[Build Status (Travis CI), link=https://travis-ci.org/opendevise/bespoke-builds]
endif::[]

Orchestrates builds in a http://markdalgleish.com/projects/bespoke.js[Bespoke.js] presentation.

== Example

//http://opendevise.github.io/bespoke-builds[View the demo] online.

This repository includes a demo folder that shows this plugin in action.
To view it locally, you first need to clone this repository:

 $ git clone https://github.com/opendevise/bespoke-builds && cd bespoke-builds

Next, install the dependencies inside the project folder using npm:

 $ npm install

Finally, visit the file [path]_demo/index.html_ in your browser to see the plugin in action.

== Download

Download the {uri-raw-file-base}/dist/bespoke-builds.min.js[production mode version] or the {uri-raw-file-base}/dist/bespoke-builds.js[development mode version], or use a package manager.

=== npm

 $ npm install bespoke-builds

=== Bower

 $ bower install bespoke-builds

== Usage

This plugin is shipped in a https://github.com/umdjs/umd[UMD format], meaning it is available as a CommonJS/AMD module or as a browser global.

For example, when using CommonJS modules:

```js
var bespoke = require('bespoke'),
  builds = require('bespoke-builds');

bespoke.from('.deck', [
  builds()
]);
```

When using a browser global:

```js
bespoke.from('.deck', [
  bespoke.plugins.builds()
]);
```

== License

http://en.wikipedia.org/wiki/MIT_License[MIT License]
